---
- name: Install git and clone a remote git repo from github
  hosts: all
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Clone a remote repo into a new folder
      git:
        repo: https://github.com/IntelliqDevops/FunctionalTesting.git
        dest: /tmp/mygit
    - name: Change permissions, ownership and group ownership of the folder where code is downloaded
      file:
        name: /tmp/mygit
        mode: 750
        owner: sai
        group: Anu
...
