---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "Intelliq"
        dest: /var/www/html/index.html
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
    - name: Check apache2 response on server 1
      uri:
        url: http://172.31.1.245
        status_code: 200
    - name: Check apache2 response on server 2
      uri:
        url: http://172.31.3.62
        status_code: 200      
...

