---
- name: configure apache2/httpd based on OS flavors
  hosts: all
  tasks:
    - block:
       - name: Install apache2 on ubuntu servers
         apt:
           name: apache2
           state: present
           update_cache: yes
      rescue:
        - name: Install httpd on Redhat servers
          yum:
            name: httpd
            state: present
            update_cache: yes
    - name: Edit the index.html file
      copy:
        content: "IntelliQ"
        dest: /var/www/html/index.html
    - block:
       - name: Restart apache2 on ubuntu servers
         service:
           name: apache2
           state: restarted
      rescue:
        - name: Restart httpd on Redhat server
          service:
            name: httpd
            state: restarted
    - name: Check apache2/httpd response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.1.245
        - http://172.31.3.62
        - http://172.31.12.198
...
