---
- name: Implementing loops
  hosts: all
  tasks:
    - name: Install java
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - openjdk-17-jdk
        - git
        - maven
...
